const events2026 = [
    // other events...
    { id: "stockholm-run-2026", title: "Stockholm Run", name: "Stockholm run", url: "https://strava.app.link/27xxFvjz71b" },
    { id: "tallinn-run-2026", title: "MRC Baltic Cruise II - Tallinn Run", name: "Tallinn run", url: "https://strava.app.link/27xxFvjz71b" },
    // other events...
];